RЗТ-697
rarible/protocol-ethereum-sdk pull request #13
Opened 2021-08-16 13:53 UTC by vitalbadjo

2021-08-16 14:39 UTC, evgenynacu requested changes

2021-08-16 14:39 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/transfer.ts
> +type TransferAsset =
it seems this should include something like NftAssetType too?

2021-08-16 14:39 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export async function mint(
can we union mint and mintLazy? so maybe just use extra param like lazy: boolean?

2021-08-17 10:25 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export async function mint(
fixed

2021-08-18 03:50 UTC, evgenynacu requested changes

2021-08-18 03:50 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export type MintRequest = SimpleNft & { isLazy: false, contract: Address, minter: Address }
it seems minter is not required here (cause there is from in Ethereum abstraction). can we check it everywhere?

2021-08-18 03:50 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +			return tx.hash ? tokenId : undefined
can hash be null or undefined?

2021-08-18 03:50 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export type MintRequest = SimpleNft & { isLazy: false, contract: Address, minter: Address }
also, can we make isLazy optional? so we can skip isLazy: false when we create request

2021-08-18 03:50 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +	uri: string
why uri is here and contract: Address is defined on line with MintRequest? Let's do it the same way

2021-08-18 03:50 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export type MintLazyRequest = SimpleLazyNft<"signatures" | "tokenId"> & { isLazy: true }
possibly, the same applies to MintLazyRequest (with minter defined - it's defined in Ethereum now) let's check it there too

2021-08-18 03:59 UTC, evgenynacu requested changes

2021-08-18 03:59 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.ts
> +	const ownership: Address = await erc721.functionCall("ownerOf", tokenId).call()
I don't think we need to make this check. This will be done in contracts, user will see error in the wallet if this isn't the case

2021-08-18 03:59 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.test.ts
> +		await testErc721.methods.setApprovalForAll(to, true)
We don't need to call this for transfer. approval is needed only if operator wants to transfer funds (if owner does this, then approval is not needed)

2021-08-18 03:59 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.test.ts
> +		const resultSenderBalance = await testErc721.methods.balanceOf(testAddress).call()
no need to check anything besides ownerOf. balanceOf not needed

2021-08-18 03:59 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc1155.test.ts
> +	test(`the transferErc1155 should return undefined,
the name differs from the test content. it returns error now. And that's very ok to throw here, not return undefined

2021-08-18 03:59 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.ts
> +	return undefined
in case of error it's good to throw, not return undefined

2021-08-18 05:19 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.ts
> +	return undefined
not actual because check for ownerships removed here https://github.com/rarible/protocol-ethereum-sdk/pull/13#discussion_r690880471

2021-08-18 05:19 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc1155.test.ts
> +	test(`the transferErc1155 should return undefined,
fixed

2021-08-18 05:23 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export type MintRequest = SimpleNft & { isLazy: false, contract: Address, minter: Address }
i agree, fixed

2021-08-18 05:23 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +			return tx.hash ? tokenId : undefined
fixed

2021-08-18 05:24 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +export type MintRequest = SimpleNft & { isLazy: false, contract: Address, minter: Address }
you are right, refactored

2021-08-18 05:24 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/mint.ts
> +	uri: string
fixed

2021-08-18 05:24 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.ts
> +	const ownership: Address = await erc721.functionCall("ownerOf", tokenId).call()
fixed

2021-08-18 05:24 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.test.ts
> +		await testErc721.methods.setApprovalForAll(to, true)
fixed

2021-08-18 05:24 UTC, vitalbadjo commented on packages/protocol-ethereum-sdk/src/nft/transfer-erc721.test.ts
> +		const resultSenderBalance = await testErc721.methods.balanceOf(testAddress).call()
fixed

2021-08-25 14:25 UTC, merged