RPN-1045: update mint examples
rarible/protocol-ethereum-sdk pull request #33
Opened 2021-09-22 15:41 UTC by mazinden

2021-09-24 09:48 UTC, evgenynacu requested changes

2021-09-24 09:48 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +	uri: "/ipfs/QmWLsBu6nS4ovaHbGAXprD1qEssJu4r5taQfB74sCG51tp",   // URI of the contract
That's URI for the token, not for the contract

2021-09-24 09:48 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +type MintForm = {
MintForm is not needed here. it's from examples project

2021-09-27 08:04 UTC, mazinden commented on packages/protocol-ethereum-sdk/README.md
> +	uri: "/ipfs/QmWLsBu6nS4ovaHbGAXprD1qEssJu4r5taQfB74sCG51tp",   // URI of the contract
fix

2021-09-29 04:12 UTC, evgenynacu requested changes
The point of this PR was to write about the whole process of minting.
Users need to check type of the collection (using provided isErc721... or isErc1155.... functions)
And then, depending on the result users should provide different requests to this function.

Also, it's good to describe response.

2021-09-29 04:12 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +Mint function checks:
I think we should first tell how to use the function (and after that we tell this we can tell what the function does internally)
So, we should tell what the function is used for.

So, here we can say for example:
You can use mint to create a token in different collections.
Depending on the collection type, different Mint requests should be sent to the function.

And there can go examples with dfifferent collection types.
Also, we should state how to distinguish between those collection types (there are functions isErc1155v1Collection, isErc1155v2Collection etc)

2021-09-29 04:12 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
>  1. Regular "on chain" minting using contract.
Also, before these lines, there is a text "There are support two ways". Which is grammatically incorrect

2021-09-29 04:12 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +		id: toAddress(contractAddress),                   // Contract address
We should remove this object and just have an example like.

```
mint({
  collection,
  uri: "uri",
  royalties: [],
  creators: [],
})
```

this is the case from mint.md

2021-09-29 04:12 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +		supportsLazyMint: true,                           // True if contract supports lazy minting
That's not about supporting lazy mint, it's about the actual mint: true means token will be lazy minted. false otherwise.
This argument won't work if collection passed doesn't support lazy mint (then anyway regular mint will be done)

2021-09-29 04:12 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +Mint function always return tokenId as string.
That's not the case too. mint returns response now

2021-09-29 04:12 UTC, evgenynacu commented on packages/protocol-ethereum-sdk/README.md
> +    return mint({
I think we can remove these code examples from this file (if we have a link to mint.md)

2021-09-30 09:31 UTC, mazinden commented on packages/protocol-ethereum-sdk/README.md
> +		id: toAddress(contractAddress),                   // Contract address
Ok changed the example

2021-09-30 10:29 UTC, mazinden commented on packages/protocol-ethereum-sdk/README.md
> +		supportsLazyMint: true,                           // True if contract supports lazy minting
ok fixed

2021-09-30 10:39 UTC, mazinden commented on packages/protocol-ethereum-sdk/README.md
> +Mint function checks:
yes, it will be much better

2021-10-01 07:49 UTC, merged